### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by HenrikoMagnifico** [MichielP1807/FoobarSongrequestYouTubeBot#3]
Hello Michiel! I am sorry that I had to commit an issue for this request, but I am quite unfamiliar with GitHub and could not figure out how to send you a DM. I've been trying to set up and use your program, FoobarSongrequestYouTubeBot, for a while now but it's giving me errors. I would really like to use this program, and I'm willing to pay you to fix it as soon as possible. Please contact me if you're interested.

Thanks!
-Henriko

**Comment by michielp1807** [comment]
Hi Henriko!

I know that the FoobarSongrequestYouTubeBot is not well maintained currently, and that is mainly due to the fact that the good people at Google have limited the amount of queries that you can use per day with the YouTube API from 1,000,000 to 10,000. This means that the bot would only be able to load new messages from the live chat every 30 seconds or so if you leave it running 24/7.

Because of this I have stopped working on the FoobarSongrequestYouTubeBot, but I have found an alternative: You can use another YouTube live chat bot (like the [Streamlabs Chatbot](https://streamlabs.com/chatbot) or [Nightbot](https://nightbot.tv)) to read the chat, and then you can have one of those bots control Foobar2000 to queue music. These chat bots have been verified by YouTube and thus they are able to perform more queries with the YouTube API.

You can send me an email at michielp1807@gmail.com if you want help setting such a system up.

-Michiel
